### PR TITLE
Codebility | CODEB-19: Refactor Applicants

### PR DESCRIPTION
**Pull request by nerwinalamas**
changes:
- refactor accept and deny action
- fix styling for mobile and desktop view

old

image

image

new

image

image

### CODE REVIEW

**Comment by reyesprince31** [comment]
@nerwinalamas pa include ng screenshot bro sa descriptio if may ui fixed, and pacheck ng additional issue sa applicants page na nakita ko.. then pa merged kagad..

**Comment by nerwinalamas** [comment]
> @nerwinalamas pa include ng screenshot bro sa descriptio if may ui fixed, and pacheck ng additional issue sa applicants page na nakita ko.. then pa merged kagad..

sa max width po yun sir every page sir naka set ata to "max-w-screen-xl mx-auto"

image

eto sya sa screen ko, sa ibang mas malaking screen iba rin sya

image

image

**Comment by reyesprince31** [comment]
image

yung skeleton loader nya kasi w-full so hindi match..

image

**Comment by nerwinalamas** [comment]
> image
> 
> yung skeleton loader nya kasi w-full so hindi match..
> 
> image

fix ko nalang loading sir

**Comment by nerwinalamas** [comment]
loading

desktop screen

image

large screen

image

medium screen

image

small screen

image

set max width and position to center

image

**Pull request merged**
